{
 "title": "CapacityDashXYZ",
 "tags": [
  "farmer_id",
  "node_id"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Days/Farmers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "farmer_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "capacitybeats",
     "select": [
      [
       { "params": [ "up" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "* 100/ (360*24)" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Days/Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "node_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "capacitybeats",
     "query": "SELECT count(\"up\") * 100/ (360*24) FROM \"capacitybeats\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "up" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "* 100/ (360*24)" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CapacityFarmers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "farmer_id" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "capacitybeats",
     "query": "SELECT count(\"up\") *1000/($__interval_ms/1000) FROM \"capacitybeats\" WHERE $timeFilter GROUP BY time($__interval), \"farmer_id\" fill(0)",
     "select": [
      [
       { "params": [ "up" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "*1000/($__interval_ms/1000)" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CapacityNodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "farmer_id" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "capacitybeats",
     "query": "SELECT count(\"up\") *1000/($__interval_ms/1000) FROM \"capacitybeats\" WHERE $timeFilter GROUP BY time($__interval), \"node_id\" fill(0)",
     "select": [
      [
       { "params": [ "up" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "*1000/($__interval_ms/1000)" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}