# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


from .RegisterFarmerHandler import RegisterFarmerHandler
from .UpdateFarmerHandler import UpdateFarmerHandler
from .ListFarmersHandler import ListFarmersHandler
from .GetFarmerHandler import GetFarmerHandler
from .ListCapacityHandler import ListCapacityHandler
from .RegisterCapacityHandler import RegisterCapacityHandler
from .GetCapacityHandler import GetCapacityHandler
from .RegisterFarmerHandler import RegisterFarmerHandler
from .UpdateFarmerHandler import UpdateFarmerHandler
from .RecordCapacityBeatHandler import RecordCapacityBeatHandler
from .UpdateReservedCapacityHandler import UpdateReservedCapacityHandler
from .UpdateActualUsedCapacityHandler import UpdateActualUsedCapacityHandler
